<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>

<div class="container-form">

    <form method="post" action="" class="form">


        <label for="password">Password: </label>
        <input type="password" name="password" id="password" class="form-control" placeholder="Enter your password" required />

        <label for="newpassword">New Password: </label>
        <input type="password" name="newpassword" id="newpassword" class="form-control" placeholder="Enter new password" required />

        <hr>
        <div class="form-group">
            <input type="submit" value="Submit">
        </div>
        <br>
    </form>
</div>