<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>

<div class="container-form">
    <h4 class="reg-form">Registration</h4>
    <form method="post" action="" class="form">
        <input type="hidden" name="id" id="id" />

        <label for="firstname">Firstname: </label>
        <input type="text" name="firstname" id="firstname" class="form-control" placeholder="Enter firstname" required />

        <label for="lastname">Lastname: </label>
        <input type="text" name="lastname" id="lastname" class="form-control" placeholder="Enter lastname" required />

        <label for="email">Email: </label>
        <input type="email" name="email" id="email" class="form-control"/>

        <label for="password">Password: </label>
        <input type="password" name="password" id="password" class="form-control" placeholder="Enter your password" required="required" />

        <label for="confirm_password">Confirm password: </label>
        <input type="password" name="confirm_password" id="confirm_password" class="form-control" placeholder="Confirm your password" required="required" />

        <label for="username">Username: </label>
        <input type="text" name="username" id="username" class="form-control" placeholder="Enter your username" required />

        <label for="phone_number">Phone number: </label>
        <input type="number" name="phone_number" id="phone_number" class="form-control" placeholder="Enter your phone number" required />

        <input type="hidden" name="role_id" value="2" class="form-control">

        <hr>
        <div class="form-group">
            <input type="submit" value="Register">
        </div>
        <br>
        <div class="quest">
            <p>Already have an account? <a href="login">Sign in</a></p>
        </div>
    </form>
</div>