<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>

<?php

if (isset($data)) {
    foreach ($data as $user) { ?>
        <div class="container-form">
            <h4 class="reg-form">Update your information</h4>
            <form method="post" action="update" class="form">
                <input type="hidden" name="id" id="id" value="<?php echo $user['id']; ?>">

                <label for="firstname">Firstname: </label>
                <input type="text" name="firstname" id="firstname" class="form-control" placeholder="Update your firstname" value="<?php echo $user['firstname']; ?>">

                <label for="lastname">Lastname: </label>
                <input type="text" name="lastname" id="lastname" class="form-control" placeholder="Update your lastname" value="<?php echo $user['lastname']; ?>">

                <label for="email">Email: </label>
                <input type="email" name="email" id="email" class="form-control" placeholder="Update your email" value="<?php echo $user['email']; ?>">

                <label for="username">Username: </label>
                <input type="text" name="username" id="username" class="form-control" placeholder="Update your username" value="<?php echo $user['username']; ?>">

                <label for="phone_number">Phone number: </label>
                <input type="number" name="phone_number" id="phone_number" class="form-control" placeholder="Update your phone number" value="<?php echo $user['phone_number']; ?>">

                <hr>
                <div class="form-group">
                    <input type="submit" name="update" value="Update">
                </div>
                <br>
            </form>
        </div>
        <?php
    }
}
?>

