<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">

    <title>Vintage-Rent</title>
    <link rel="stylesheet" href="<?php echo \Application\Lib\Config::config('url') ?>public/css/style.css" type="text/css" />
</head>
<body>
    <div class="head-nav">
        <h1 class="head"><a href="<?php echo SITE_ROOT;?>/CarController/index">Vintage Rent-a-car</a></h1>

        <?php require dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR . 'navbar.phtml'; ?>

    </div>

    <div class="container">






